#name: Build And Deploy TO Aliyun ECS
name: Lint And Build

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '18' ]
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: master
      - name: use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: use Pnpm
        run: npm install -g pnpm
      - name: install
        run: |
          pnpm install
          pnpm lint
          pnpm build
#      - name: deploy
#        uses: easingthemes/ssh-deploy@v2
#        env:
#          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
#          ARGS: '-avzr --delete'
#          SOURCE: "dist/"
#          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
#          REMOTE_USER: ${{ secrets.REMOTE_USER }}
#          TARGET: ${{ secrets.REMOTE_TARGET }}
