  name:Build And Deploy TO Aliyun ECS

  on:
    push:
      branches:
        - master

  jobs:
    build-and-deploy:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          node-version: [ 16.x ]
      steps:
        - name: checkout
          uses: actions/checkout@v2
          with:
            ref: master
        - name: install
          run: |
            npm install
            npm run-script lint
            npm run-script build
        - name: deploy
          uses: easingthemes/ssh-deploy@v2
          env:
            SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
            ARGS: '-rltgoDzvO --delete'
            SOURCE: "dist/"
            REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
            REMOTE_USER: ${{ secrets.REMOTE_USER }}
            TARGET: ${{ secrets.REMOTE_TARGET }}
